# Generated by Django for InkFlow.

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_alter_post_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('Articles', 'Articles'), ('Poems', 'Poems'), ('Stories', 'Stories')], default='Articles', max_length=20),
        ),
    ]
